# Generated by Django 5.0.6 on 2024-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_description_en_project_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_es',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
    ]
