# Generated by Django 5.0.6 on 2024-06-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специализации', 'verbose_name_plural': 'Специализации'},
        ),
    ]
