# Generated by Django 5.0.6 on 2024-06-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_options_skill_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='specialization',
        ),
    ]
