# Generated by Django 5.0.6 on 2024-06-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_remove_skill_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_es',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
    ]
